name: first workflow
on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v1

      - name: call custom action
        id: call_api
        uses: ./.github/actions/getvariables
        with:
          api_url: 'https://icanhazdadjoke.com/'
          api_token: 'dsdsdsdsd'
      - name: run echo
        run: echo "Hello first workflow"
      - name: print the outputs
        run: echo ${{steps.call_api.output.api_response}}
