name: first workflow
on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello first workflow"

  run-shell-command2:
    runs-on: maxOS
    steps:
      - name: echo a string
        run: echo date
